const CHATBOT_ACTION_TYPES = {
    ADD_CHAT_MESSAGE: 'ADD_CHAT_MESSAGE',
    UPDATE_BOT_MESSAGE: 'UPDATE_BOT_MESSAGE',
    TOGGLE_QUERY_RATING_BTN_DISABLED_STATUS: 'TOGGLE_QUERY_RATING_BTN_DISABLED_STATUS'
};

export default CHATBOT_ACTION_TYPES;